services:
  database:
    image: mongo
    container_name: museum_quiz_database
    restart: always
    volumes:
      - type: bind
        source: ./data
        target: /data/db
    ports:
      - "27017:27017"
  backend:
    build: backend
    container_name: museum_quiz_backend
    restart: always
    environment:
      MONGODB_HOST: mongodb://database:27017
    ports:
      - "8000:8000"
    volumes:
      - media:/museum_quiz_backend/media
    depends_on:
      - database

  frontend:
    build: frontend
    container_name: museum_quiz_frontend
    restart: always
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend
      - database

volumes:
  media:
    driver: local
    driver_opts:
      type: none
      device: /media
      o: bind